#!/usr/bin/env bash
# PreToolUse hook (Edit|Write|MultiEdit): block edits to generated files and secrets.
# Exit 2 blocks the tool call and returns stderr to Claude as feedback.
set -euo pipefail

input=$(cat)
file=$(printf '%s' "$input" | jq -r '.tool_input.file_path // .tool_input.path // empty')
[ -z "$file" ] && exit 0

block() {
  echo "BLOCKED by .claude/hooks/protect-paths.sh: $1" >&2
  exit 2
}

# Allow the committed template files through before matching secrets below.
case "$file" in
  *.example) exit 0 ;;
esac

case "$file" in
  */routeTree.gen.ts)
    block "apps/web/src/routeTree.gen.ts is generated by TanStack Router. Don't hand-edit it — it regenerates on \`pnpm dev:web\` / build. Edit the route files under apps/web/src/routes/ instead." ;;
  */packages/db/drizzle/*)
    block "packages/db/drizzle/ is generated by drizzle-kit and is a do-not-hand-edit directory. Edit packages/db/src/schema.ts, then run \`pnpm db:generate\` followed by \`pnpm db:migrate\`." ;;
  */.dev.vars|*/.env|*/.env.local|*/.env.*.local|*/wrangler.local.jsonc)
    block "Refusing to write local/secret config ($file). These hold credentials and are gitignored or generated. Edit the committed *.example template, or regenerate via \`pnpm setup:local\`." ;;
esac

exit 0
