/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistryIndexRouteImport } from './routes/registry/index'
import { Route as RegistryOrgSlugRouteImport } from './routes/registry/$org/$slug'
import { Route as OrgsOrgIdSkillsSlugRouteImport } from './routes/orgs/$orgId/skills/$slug'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryOrgSlugRoute = RegistryOrgSlugRouteImport.update({
  id: '/registry/$org/$slug',
  path: '/registry/$org/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgIdSkillsSlugRoute = OrgsOrgIdSkillsSlugRouteImport.update({
  id: '/orgs/$orgId/skills/$slug',
  path: '/orgs/$orgId/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/registry/': typeof RegistryIndexRoute
  '/registry/$org/$slug': typeof RegistryOrgSlugRoute
  '/orgs/$orgId/skills/$slug': typeof OrgsOrgIdSkillsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/registry': typeof RegistryIndexRoute
  '/registry/$org/$slug': typeof RegistryOrgSlugRoute
  '/orgs/$orgId/skills/$slug': typeof OrgsOrgIdSkillsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/registry/': typeof RegistryIndexRoute
  '/registry/$org/$slug': typeof RegistryOrgSlugRoute
  '/orgs/$orgId/skills/$slug': typeof OrgsOrgIdSkillsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/observability'
    | '/settings'
    | '/registry/'
    | '/registry/$org/$slug'
    | '/orgs/$orgId/skills/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/observability'
    | '/settings'
    | '/registry'
    | '/registry/$org/$slug'
    | '/orgs/$orgId/skills/$slug'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/observability'
    | '/settings'
    | '/registry/'
    | '/registry/$org/$slug'
    | '/orgs/$orgId/skills/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ObservabilityRoute: typeof ObservabilityRoute
  SettingsRoute: typeof SettingsRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
  RegistryOrgSlugRoute: typeof RegistryOrgSlugRoute
  OrgsOrgIdSkillsSlugRoute: typeof OrgsOrgIdSkillsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/': {
      id: '/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$org/$slug': {
      id: '/registry/$org/$slug'
      path: '/registry/$org/$slug'
      fullPath: '/registry/$org/$slug'
      preLoaderRoute: typeof RegistryOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId/skills/$slug': {
      id: '/orgs/$orgId/skills/$slug'
      path: '/orgs/$orgId/skills/$slug'
      fullPath: '/orgs/$orgId/skills/$slug'
      preLoaderRoute: typeof OrgsOrgIdSkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ObservabilityRoute: ObservabilityRoute,
  SettingsRoute: SettingsRoute,
  RegistryIndexRoute: RegistryIndexRoute,
  RegistryOrgSlugRoute: RegistryOrgSlugRoute,
  OrgsOrgIdSkillsSlugRoute: OrgsOrgIdSkillsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
